spring:
  profiles:
    active: dev
  application:
    name: empty
  datasource:
    url: jdbc:mysql://221.229.208.19:3306/stat_test_copy?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: ehl1234
  activemq:
    broker-url: tcp://157.0.243.29:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000

mybatis:
  typeAliasesPackage: com.ehl.tsq.data.infrastructure.persistence.po
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

threadPool:
  corePoolSize: 50
  maxPoolSize: 80
  queueCapacity: 9999
  keepAliveSeconds: 60

server:
  port: 22001

ZHCG:
  vehicles_page: http://157.0.243.32:18188/sanitation/settings/vehicles/page
  vehicles_track: http://157.0.243.32:18188/sanitation/overview/vehicles/track/history/
  toilets_page: http://157.0.243.32:18188/sanitation/settings/toilets/page
  stations_page: http://157.0.243.32:18188/sanitation/settings/stations/page
  trashes_page: http://157.0.243.32:18188/sanitation/settings/trashes/page
  muck_tree: http://157.0.243.27:18097/view/muck/tree
  muck_track: http://157.0.243.27:18097/view/muck/history/track/
