
server:
  port: 22010
  server:
    servlet:
      context-path: /ferry
spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  kafka:
    bootstrap-servers: 192.168.227.141:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
